### PR TITLE
Add aur package

### PR DESCRIPTION
**Pull request by jneidel**
I've created an AUR package and added it to the install section.

### CODE REVIEW

**Comment by olblak** [comment]
Hi @jneidel
Thanks for this initiative.
Does it get updated automatically after each Updatecli release or is there something else we should be doing?

**Comment by jneidel** [comment]
I've subscribed to you Github Releases and will continuously update the package 😄 
There's nothing that needs to be done on your end 🚀

**Comment by olblak** [comment]
> I've subscribed to you Github Releases and will continuously update the package smile There's nothing that needs to be done on your end rocket

Thanks for the proposition, I had a quick look at Goreleaser, the tool that handle release and apparently it can automatically publish on AUR soI think in mid-term.

->https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L180L205

**Comment by jneidel** [comment]
If you want to look into and configure it, go ahead. I'll cede package ownership if you want to take the package over :+1:

**Comment by olblak** [comment]
@jneidel I created an AUR account named "olblak" and I would be interested to have package co-ownership with you. I am not an arch linux user. 

I added the AUR key and the goreleaser seems ready so I am ready to release a version 0.44.3 to update the arch linux

**Pull request merged**
